---
format:
  html:
    theme: minty
  PrettyPDF-pdf:
    pdf-engine: latexmk
    pdf-engine-opt: -xelatex
---

```{r}
#| echo: false
#| message: false

setwd(here::here())
```

# Giulia Mazzola

*she, lei, idda, ella, zij*

[giulia.mazzola\@ncl.ac.uk](mailto:giulia.mazzola@ncl.ac.uk) \| [giuliamazzola.github.io](https://giuliamazzola.github.io/) \| ORCID:[0000-0002-7532-8671](https://orcid.org/0000-0002-7532-8671)</a>

## About me

I am a usage-based linguist and my research explores the interplay of cognitive, sociolinguistic, and historical perspectives on Romance morphosyntax. I have a strong passion for innovative and cross-disciplinary methodologies and I believe in the importance of open-access and FAIR principles. My academic dream is to build linguistic corpora to document and protect endangered languages. I am deeply committed to fostering research-led teaching, integrating cutting-edge linguistic insights in the curricula. With a strong foundation in international collaboration, I strive to advance impactful scholarship while promoting diversity, innovation, and equality in academia.

## Work Experience

| Year              | Position                                     | Institution                   |
|------------------|--------------------------------|----------------------|
| 06/2024 - Present | **Research Associate**                       | Newcastle University          |
| 01/2023 - 06/2024 | **Postdoctoral Assistant**                   | KU Leuven                     |
| 10/2018 - 12/2022 | **PhD student**                              | KU Leuven                     |
| 11/2017 - 02/2018 | **Teacher of Italian as a Foreign Language** | Rotterdamse Volksuniversiteit |
| 10/2016 - 05/2017 | **Internship Foreign Language Teaching**     | Universiteit Leiden           |

## Education

| Year        | Degree                                                  | Institution                       |
|------------------|--------------------------------|-----------------------|
| 2018 - 2022 | **PhD in Linguistics**                                  | KU Leuven                         |
| 2015 - 2018 | **Research Master in Linguistics**                      | Universiteit Leiden               |
| 2010 - 2014 | **Bachelor degree in Modern Languages and Literatures** | Università degli studi di Palermo |

## Research Projects

#### Research Associate - [How autonomous is syntax? A case study of Romance causation and perception](https://www.caurpe.org/home)\newline

2024-present, Newcastle University (UK) (PI Michelle Sheehan)

#### International collaborator - [Atlas Histórico del español](https://atlashistorico.uib.es/)\newline

2022-2024, University of the Balearic Islands (ES) (PI Andrés Enrique-Arias)

#### International collaborator - [Historical and typological perspectives on anticausativization](https://sites.google.com/view/guglielmoinglese/research)\newline

2022-2024, Università di Torino (IT) (PI Guglielmo Inglese)

#### PhD student - [Beyond the clause: encoding and inference in clause-combining](https://sites.google.com/view/beyondtheclause/home)\newline

2018-2022, KU Leuven (BE) (PI Jean-Christophe Verstraete)

#### Student Assistant - [Haagse Spreuken](https://www.haagsespreuken.nl/)\newline

2017, Universiteit Leiden (NL), outreach project on multilingualism

## Teaching

#### Undergraduate module of *Spaanse Taalkunde III* (Spanish Linguistics III)\newline 

February-June 2023 and 2024, KU Leuven - 4 ECTS

-   History of the Spanish Language
-   Historical Phonology
-   Historical Morpho-syntax
-   Philological analysis of ancient texts

#### Undergraduate module of *Spaanse Taalkunde II* (Spanish Linguistics II)\newline 

September-December 2023, KU Leuven, campus Leuven and Kortrijk - 6 ECTS each

-   Morphosyntax and semantics of the contemporary Spanish verbal system
-   Analysis of contemporary texts

#### Undergraduate spoken practice of *Spaans: taal & tekts* (Spanish: language and texts)\newline

March-May 2023, KU Leuven

-   Conversation practice in Spanish (second year of the undergraduate program, 2 hours per week)

## Publications

### Peer-reviewed publications

#### Journal Articles

-   Mazzola, Giulia, Malte Rosemeyer, and Bert Cornillie. 2022. “Syntactic Alternations and Socio-Stylistic Constraints: The Case of Asyndetic Complementation in the History of Spanish.” *Journal of Historical Sociolinguistics* 8 (2): 197–235. <https://doi.org/10.1515/jhsl-2021-0026>.

-   Mazzola, Giulia, Bert Cornillie, and Malte Rosemeyer. 2022. “Asyndetic Complementation and Referential Integration in Spanish: A Diachronic Probabilistic Grammar Account.” *Journal of Historical Linguistics* 12 (2): 194–240. <https://doi.org/10.1075/jhl.20031.maz>.

#### Edited Volumes

-   Cornillie, Bert, Giulia Mazzola, and Miriam Thegel (eds.). 2023. *La Tradicionalidad Discursiva y La Lingüística de Corpus. Conceptos y Aplicaciones*. Madrid/Frankfurt a.M.: Iberoamericana Vervuert.

#### Book Chapters

-   Mazzola, Giulia, Stefano De Pascale, and Malte Rosemeyer. 2023. “Nuevas Herramientas En La Lingüística Diacrónica: Tradiciones Discursivas y Lingüística Computacional.” In *La Tradicionalidad Discursiva y La Lingüística de Corpus. Conceptos y Aplicaciones*, edited by Bert Cornillie, Giulia Mazzola, and Miriam Thegel, 89–118. Madrid/Frankfurt a.M.: Iberoamericana Vervuert.

-   Cornillie, Bert, and Giulia Mazzola. 2021. “A Sociopragmatic Account of the Se Passive in (Pre-)Classical Spanish.” In *Cognitive Sociolinguistics Revisited*, edited by Gitte Kristiansen, Karlien Franco, Stefano De Pascale, Laura Rosseel, and Weiwei Zhang, 226–41. Berlin: De Gruyter. <https://doi.org/10.1515/9783110733945-019>.

### Non-peer-reviewed publications

-   Mazzola, Giulia. 2024. Las subordinadas asindéticas en sus orígenes: un análisis de la distribución geográfica en los siglos XV y XVI. In *Atlas Histórico del Español* (PI Andrés Enrique-Arias). [Online publication](https://atlashistorico.uib.es/cap/Mazzola1).

### Work in progress

#### Accepted

-   Inglese, Guglielmo, Eugenio Goria and Giulia Mazzola (eds.). *Diachronic and Typological Perspectives on Anticausativization*. Series: *Typological Studies in Language*. Amsterdam: John Benjamins.

-   Inglese, Guglielmo, Giulia Mazzola, Eugenio Goria, Lorenzo Ferrarotti and Bert Cornillie. (forthc.) "Anticausativization and lability in Romance: a historical corpus study on Spanish and Italian". In Inglese, Guglielmo, Eugenio Goria and Giulia Mazzola (eds.), *Diachronic and Typological Perspectives on Anticausativization* (series *Typological Studies in Language)*. Amsterdam: John Benjamins.

-   Mazzola, Giulia, Guglielmo Inglese. Forthcoming. "Causalness, frequency, diachrony and the causal-noncausal alternation in Italian and Spanish". *Corpus linguistics and linguistic theory*.

#### In preparation

-   Mazzola, Giulia. "Processing constraints in competition: a case study of syndetic and asyndetic complements in Spanish". *Cognitive Linguistics*

-   Mazzola, Giulia, Stefano De Pascale, Malte Rosemeyer. Document-based Vector Space Models predict diffusion in language change better than genre classifications. *Linguistic Vanguard*

### PhD Thesis

-   Mazzola, Giulia. 2022. “Syndetic and Asyndetic Complementation in Spanish. A Diachronic Probabilistic Account.” PhD Thesis, Leuven: KU Leuven. [Download here](https://lirias.kuleuven.be/retrieve/688775)

## Talks

### Invited Lectures

-   Sheehan, M., Mazzola, G. (2024). How autonomous is syntax? A micro-syntactic perspective. Invited talk given at the *Meaning and Grammar Research Group*, Edinburgh University, Edinburgh.

-   Mazzola, G., Sheehan, M. (2024). Causation and perception: how similar are they? Invited talk at *Philosophy of Linguistics Workshop*, Durham University, Durham.

-   Inglese, G., Mazzola, G. (2024). "Anticausatives in Italian and Spanish across time: a corpus-based perspective". Humboldt-Universität zu Berlin, *Colloquium Romanistische Linguistik*, Berlin.

-   Mazzola, G. (2023). "La complementación asindética en español". University of Helsinki, Helsinki.

-   Mazzola, G. (2022). "Approcci descrittivi e probabilistici alla linguistica dei corpora. Esempi applicati alla complementazione in spagnolo". Università di Torino, Torino.

-   Mazzola, G. (2022). "La Complementación asindética en Español: un estudio diacrónico". Freie Universität Berlin, Berlin.

-   Mazzola, G. (2021). "La complementación asindética en castellano: un estudio diacrónico". Universität Regensburg, *Linguistics Colloquium*, Regensburg.

### Selected Conference Talks

#### 2024

-   Mazzola, G. Processing constraints in competition: a case study of syndetic and asyndetic complements in Spanish. Presented at *Annual meeting of the Linguistics Association of Great Britain and Northern Ireland* (LAGB 2024, 27-30 August 2024), Newcastle University, Newcastle upon Tyne.

-   Mazzola, G. La complementación asindética en el español (pre)clásico: ¿una influencia oriental?. Presented at the *VIII Congreso Internacional de la Red CHARTA* (19-21 June 2024), Universitat de les Illes Balears, Palma de Mallorca.

#### 2023

-   Inglese, G., Mazzola, G., Ferrarotti, L., Goria, E., Cornillie, B. "The anticausative alternation in Italian and Spanish: a historical corpus-based perspective". Presented at the *International conference on Historical Linguistics* (ICHL26), University of Heidelberg, Heidelberg.

-   Inglese, G., Ferrarotti, L., Goria, E., Mazzola, G., and Cornillie, B. “The anticausative alternation in Italian and Spanish: a historical corpus-based perspective”. Presented 56^th^ *Annual Meeting of the Societas Linguistica Europaea*, National and Kapodistrian University of Athens, Athens.

-   Mazzola, G. “Processing factors in contrast: a case study of syndetic and asyndetic complements in Spanish”. Presented 56^th^ *Annual Meeting of the Societas Linguistica Europaea*, National and Kapodistrian University of Athens, Athens.

-   Mazzola, G., De Pascale, S., Rosemeyer, M. "A Computational Approach to Detect Discourse Traditions and Register Differences. A Case Study on Historical French". Presented at the *12th Historical Sociolinguistics Network conference*, Vrije Universiteit Brussel, Brussels.

#### 2022

-   Cornillie, B., Mazzola, G. “Un análisis de la pasiva en el español (pre)clásico en CODEA+2015”. Presented at *VI CoDiLi*, Università Ca’ Foscari, Venezia.

-   De Pascale, S., Mazzola, G., Rosemeyer, M. “Vector Space Models for Historical Sociolinguistics: bottom-up classification of Discourse Traditions”. Presented at the *11th Historical Sociolinguistics Network Conference 2022,* Universidad de Murcia, Murcia.

-   Mazzola, G. “Las sustantivas asindéticas en la historia del español”. Presented at *XII Congreso Internacional de Historia de la Lengua Española.* Universidad León, León.

#### 2021

-   Mazzola, G. “Syntactic alternations and audience design: The case of asyndetic complementation in the history of Spanish (15th-18th century)”. Presented at the *New ways of analyzing variation 49* (NWAV49), online.

-   Mazzola, G. “From distance to immediacy? Asyndetic complementation in Classical and Present-day Spanish”. Presented at the *17^th^ International Pragmatics Association Conference*, hosted by Zurich University of Applied Sciences (ZHAW), online.

-   Mazzola, G., De Pascale, S. “Nuevas herramientas en la lingüística diacrónica: tradiciones discursivas y lingüística computacional”. Presented at the workshop *Las Tradiciones Discursivas en tiempos de lingüística cuantitativa: ¿corrección epistemológica o deconstrucción metodológica?*, hosted by KU Leuven, online.

-   Cornillie, B., Mazzola, G., Thegel, M. "Las Tradiciones Discursivas en tiempos de lingüística cuantitativa: ¿corrección epistemológica? ¿deconstrucción metodológica?". Introduction to the workshop *Las Tradiciones Discursivas en tiempos de lingüística cuantitativa: ¿corrección epistemológica o deconstrucción metodológica?,* hosted by KU Leuven, online.

#### 2020

-   Mazzola, G., Cornillie, B., Rosemeyer, M., De Pascale, S. “Socio-stylistic aspects of syntactic variation: the case of Spanish asyndetic complementation (15^th^-18^th^ c.)”. Presented at the *53^rd^ Annual Meeting of the Societas Linguistica Europaea (SLE)*, online.

-   Mazzola, G., Cornillie, B., Rosemeyer, M. (2020). "La complementación asindética entre el S XV y el S XVIII: Variación socioestilística". Presented at the *Jornada digital de sintaxis española – Digital Workshop on Spanish Syntax*, hosted by Heinrich-Heine-Universität Düsseldorf, online.

#### 2019

-   Mazzola, G., Rosemeyer, M., Cornillie, B. “La complementación asindética entre el S XV y el S XVIII: Variación socio-estilística”. Presented at the *CoDiLi V*, Université libre de Bruxelles, Brussels.

-   Mazzola, G., Rosemeyer, M., Cornillie, B. “The role of coreferentiality in Spanish *que*-omission between the 15th and the 18th century”. Presented at the *52^nd^ annual meeting of the Societas Linguistica Europaea (SLE)*, Universität Leipzig, Leipzig.

#### Previous years

-   Mazzola, G. "*Mij* and *mijn* in Dutch: a historical sociolinguistics study". Presented at 12th TWIST Student Conference for Linguistics (2018), Universiteit Leiden, Leiden.

-   Mazzola, G., Sánchez-Molina, S., Sorgini, L. "Synchronic evidence of a diachronic process: the grammaticalization of TENERE in Romance". Poster presented at 11th TWIST Student Conference for Linguistics (2017), Universiteit Leiden, Leiden.

## Outreach

-   Markey, M.A., Mazzola, G., Shaw, M., [“The impostor’s voice: Causes of and remedies for pluralistic self-doubt”](https://howtobecomearesearcher.wordpress.com/2023/08/22/the-impostors-voice-causes-of-and-remedies-for-pluralistic-self-doubt/?fbclid=IwAR3gzKA6gWFScBXKKhsEdMm2-XnKxSKnmLvo23X2sCtJQYmyt3X3NSUCoWw_aem_AZ11E23_jc7BxJV8sOQp3QK2_uoE_ELw8QcVx7qIVpE-IQvyP-4g2femJQIIeAYmYw4), in [Becoming a researcher](https://howtobecomearesearcher.wordpress.com/).

-   Markey, M.A., Mazzola, G., Shaw, M., [“D-day, or how to survive and thrive at your PhD defence”](https://howtobecomearesearcher.wordpress.com/2023/03/14/d-day-or-how-to-survive-and-thrive-at-your-phd-defence/), in [Becoming a researcher](https://howtobecomearesearcher.wordpress.com/).

-   Meissl, K., Mazzola, G., Montes, M., [“Bibliography chaos? Zotero your troubles away!”](https://howtobecomearesearcher.wordpress.com/2021/12/16/bibliography-chaos-zotero-your-troubles-away/), in [Becoming a researcher](https://howtobecomearesearcher.wordpress.com/).

-   Mazzola, G., Kerkhof, A., [“Doet mèn maah een bieahtje: het gebruik van mijn voor mij in het zeventiende-eeuwse Nederlands”](https://neerlandistiek.nl/2019/03/doet-men-maah-een-bieahtje-het-gebruik-van-mijn-voor-mij-in-het-zeventiende-eeuwse-nederlands/), Online article in [*Neerlandistiek- online tijdschrift voor taal- en letterkunde*](https://neerlandistiek.nl/).

## Reviewing

Topics: Morphosyntax, Romance languages, Historical Linguistics, Corpus Linguistics, Inferential Statistics, Complementation, Voice-encoding strategies

Journals: - *Journal of Linguistics* - *Isogloss* - *Anuari de Filología* - *Journal of Pragmatics* - *Bulletin of Hispanic studies* - *STUF - Language Typology and Universals*

## Skills and training

### Language skills

| Language     | Level        | Certificate | Competence                                                                                  |
|-------------|-------------|-------------|---------------------------------|
| **Italian**  | Native       |             |                                                                                             |
| **Sicilian** | Native       |             |                                                                                             |
| **English**  | Fluent       | IELTS 7.0   | Full professional competence (peer-reviewing, publishing and teaching)                      |
| **Spanish**  | Fluent       | DELE C1     | Full professional competence (peer-reviewing, publishing and teaching)                      |
| **Dutch**    | Intermediate | ITNA B2     | Full proficiency in informal settings, limited working competence                           |
| **French**   | Basic        | DELF A2     | Elementary active competence in informal settings, high competence in reading and listening |

### Technical skills

| Category                        | Type                                        |
|-------------------------------|-----------------------------------------|
| Programming language            | R (advanced), Python and HTML (basic)       |
| Document authoring tools        | Rmarkdown, Quarto, LateX, Obsidian, MS Word |
| Data management and control     | Git, GitHub                                 |
| Bibliography management         | Zotero, Mendley, BibTeX                     |
| Teaching and learning platforms | Blackboard, Canvas, Microsoft Teams         |
| Linguistics software            | ELAN, Praat, AntConc                        |
| Productivity tools              | MS Office Suite, Slack, Google Workspace    |

### Additional Training

-   LOT Summer School (Utrecht 2016)
-   LOT Winter School (Nijmegen 2017)
-   LOT Summer School (Leiden 2017)
-   LOT Winter School (Amsterdam 2019)
-   Fundamental Statistics (KU Leuven 2019)
-   Advanced R Programming (KU Leuven 2020)
-   Academic Writing (KU Leuven 2020)
-   Web Development Workshop (Newcastle 2024)
