---
bibliography: publications.bib
---

# Peer-reviewed publications

-   Mazzola, Giulia, Stefano De Pascale, and Malte Rosemeyer. 2023. “Nuevas Herramientas En La Lingüística Diacrónica: Tradiciones Discursivas y Lingüística Computacional.” In *La Tradicionalidad Discursiva y La Lingüística de Corpus. Conceptos y Aplicaciones*, edited by Bert Cornillie, Giulia Mazzola, and Miriam Thegel, 89–118. Madrid/Frankfurt a.M.: Iberoamericana Vervuert.

-   Cornillie, Bert, Giulia Mazzola, and Miriam Thegel (eds.). 2023. *La Tradicionalidad Discursiva y La Lingüística de Corpus. Conceptos y Aplicaciones*. Madrid/Frankfurt a.M.: Iberoamericana Vervuert.

-   Mazzola, Giulia, Malte Rosemeyer, and Bert Cornillie. 2022. “Syntactic Alternations and Socio-Stylistic Constraints: The Case of Asyndetic Complementation in the History of Spanish.” *Journal of Historical Sociolinguistics* 8 (2): 197–235. <https://doi.org/10.1515/jhsl-2021-0026>.

-   Mazzola, Giulia, Bert Cornillie, and Malte Rosemeyer. 2022. “Asyndetic Complementation and Referential Integration in Spanish: A Diachronic Probabilistic Grammar Account.” *Journal of Historical Linguistics* 12 (2): 194–240. <https://doi.org/10.1075/jhl.20031.maz>.

-   Cornillie, Bert, and Giulia Mazzola. 2021. “A Sociopragmatic Account of the Se Passive in (Pre-)Classical Spanish.” In *Cognitive Sociolinguistics Revisited*, edited by Gitte Kristiansen, Karlien Franco, Stefano De Pascale, Laura Rosseel, and Weiwei Zhang, 226–41. Berlin: De Gruyter. <https://doi.org/10.1515/9783110733945-019>.

# Work in progress

## Accepted

-   Inglese, Guglielmo, Eugenio Goria and Giulia Mazzola (eds.). *Diachronic and Typological Perspectives on Anticausativization*. Series: *Typological Studies in Language*. Amsterdam: John Benjamins.

## In preparation

-   Inglese, Guglielmo, Giulia Mazzola, Eugenio Goria, Lorenzo Ferrarotti and Bert Cornillie. (forthc.) "Anticausativization and lability in Romance: a historical corpus study on Spanish and Italian". In Inglese, Guglielmo, Eugenio Goria and Giulia Mazzola (eds.), *Diachronic and Typological Perspectives on Anticausativization* (series *Typological Studies in Language)*. Amsterdam: John Benjamins.

# PhD Thesis

-   Mazzola, Giulia. 2022. “Syndetic and Asyndetic Complementation in Spanish. A Diachronic Probabilistic Account.” PhD Thesis, Leuven: KU Leuven.

# Invited Lectures

-   Sheehan, M., Mazzola, G. (2024). How autonimous is syntax? A micro-syntactic perspective. Invited talk given at the *Meaning and Grammar Research Group*, Edinburgh University, 5 November.

-   Mazzola, G., Sheehan, M. (2024). Causation and perception: how similar are they? Invited talk at *Philosophy of Linguistics Workshop*, Durham University, 22 October. 

-   Inglese, G., Mazzola, G. (2024). "Anticausatives in Italian and Spanish across time: a corpus-based perspective". Invited by Humboldt-Universität zu Berlin, *Colloquium Romanistische Linguistik*, Berlin.

-   Mazzola, G. (2023). "La complementación asindética en español". Invited by University of Helsinki, Helsinki.

-   Mazzola, G. (2022). "Approcci descrittivi e probabilistici alla linguistica dei corpora. Esempi applicati alla complementazione in spagnolo". Invited by Università di Torino. Torino.

-   Mazzola, G. (2022). "La Complementación asindética en Español: un estudio diacrónico". Invited by Freie Universität Berlin, Berlin.

-   Mazzola, G. (2021). "La complementación asindética en castellano: un estudio diacrónico". Invited by Universität Regensburg, *Linguistics Colloquium*, Regensburg.

# Conference Talks

## 2023

-   Inglese, G., Ferrarotti, L., Goria, E., Mazzola, G., Cornillie, B. "How do anticausatives spread: a contrastive historical study of Italian and Spanish". Presented at the workshop *Diachronic and Typological Perspectives on Anticausativization*, Università di Torino, Turin.

-   Inglese, G., Mazzola, G., Ferrarotti, L., Goria, E., Cornillie, B. "The anticausative alternation in Italian and Spanish: a historical corpus-based perspective". Presented at the *International conference on Historical Linguistics* (ICHL26), Heidelberg.

-   Rosemeyer, M., Mazzola, G., and De Pascale, S. “A computational approach to detect discourse traditions and register differences: a case study on historical French”. 26^th^ *International Conference on Historical Linguistics* (ICHL26), Heidelberg.

-   Inglese, G.,  Ferrarotti,  L.,  Goria, E., Mazzola, G., and Cornillie, B. “The anticausative alternation in Italian and Spanish: a historical corpus-based perspective”. Presented 56^th^ *Annual Meeting of the Societas Linguistica Europaea*, National and Kapodistrian University of Athens,Athens.

-   Mazzola, G. “Processing factors in contrast: a case study of syndetic and asyndetic complements in Spanish”. Presented 56^th^ *Annual Meeting of the Societas Linguistica Europaea*, National and Kapodistrian University of Athens,Athens.

-   Mazzola, G., De Pascale, S., Rosemeyer, M. "A Computational Approach to Detect Discourse Traditions and Register Differences. A Case Study on Historical French". Presented at the *12th Historical Sociolinguistics Network conference*, Vrije Universiteit Brussel, Brussels.

## 2022

-   Cornillie, B., Mazzola, G. “Un análisis de la pasiva en el español (pre)clásico en CODEA+2015”. Presented at *VI CoDiLi*, Università Ca’ Foscari, Venezia.

-   De Pascale, S., Mazzola, G., Rosemeyer, M. “Vector Space Models for Historical Sociolinguistics: bottom-up classification of Discourse Traditions”. Presented at the *11th Historical Sociolinguistics Network Conference 2022,* Universidad de Murcia, Murcia.

-   Mazzola, G. “Las sustantivas asindéticas en la historia del español”. Presented at *XII Congreso Internacional de Historia de la Lengua Española.* Universidad León, León.

## 2021

-   Mazzola, G. “Syntactic alternations and audience design: The case of asyndetic complementation in the history of Spanish (15th-18th century)”. Presented at the *New ways of analyzing variation 49* (NWAV49), online.

-   Mazzola, G. "From Distance to Immediacy? Asyndetic complements in Classical and Present-day Spanish". 54^th^ *Annual Meeting of the Societas Linguistica Europaea,* online.

-   Mazzola, G. “From distance to immediacy? Asyndetic complementation in Classical and Present-day Spanish”. Presented at the *17^th^ International Pragmatics Association Conference*, hosted by Zurich University of Applied Sciences (ZHAW), online.

-   Mazzola, G., De Pascale, S. “Nuevas herramientas en la lingüística diacrónica: tradiciones discursivas y lingüística computacional”. Presented at the workshop *Las Tradiciones Discursivas en tiempos de lingüística cuantitativa: ¿corrección epistemológica o deconstrucción metodológica?*, hosted by KU Leuven, online.

-   Cornillie, B., Mazzola, G., Thegel, M. "Las Tradiciones Discursivas en tiempos de lingüística cuantitativa: ¿corrección epistemológica? ¿deconstrucción metodológica?". Presented at the workshop *Las Tradiciones Discursivas en tiempos de lingüística cuantitativa: ¿corrección epistemológica o deconstrucción metodológica?,* hoster by KU Leuven, online.

## 2020

-   Mazzola, G., Cornillie, B., Rosemeyer, M. “Asyndetic complementation and referential integration in Spanish: a diachronic probabilistic grammar account”. Presented at the *Taaldag 2020* (organized by the Linguistic Society of Belgium), online. Winner of the best presentation award.

-   Mazzola, G., Cornillie, B., Rosemeyer, M., De Pascale, S. “Socio-stylistic aspects of syntactic variation: the case of Spanish asyndetic complementation (15^th^-18^th^ c.)”. Presented at the *53^rd^ Annual Meeting of the Societas Linguistica Europaea (SLE)*, online.

-   Mazzola, G., Cornillie, B., Rosemeyer, M. (2020). "La complementación asindética entre el S XV y el S XVIII: Variación socioestilística". Presented at the *Jornada digital de sintaxis española – Digital Workshop on Spanish Syntax*, hoster by Heinrich-Heine-Universität Düsseldorf, online.

## 2019

-   Mazzola, G., Rosemeyer, M., Cornillie, B. “La complementación asindética entre el S XV y el S XVIII: Variación socio-estilística”. Presented at the *CoDiLi V*, Université libre de Bruxelles, Brussels.

-   Mazzola, G., Rosemeyer, M., Cornillie, B. “The role of coreferentiality in Spanish *que*-omission between the 15th and the 18th century”. Presented at the *52^nd^ annual meeting of the Societas Linguistica Europaea (SLE)*, Universität Leipzig, Leipzig.

-   Mazzola, G., Cornillie, B., Rosemeyer, M. "La omisión de que (1400 -1799): Variación estilística y morfosintáctica". Presented at the workshop *La oración compleja y las tradiciones discursivas*, KU Leuven, Leuven.

-   Mazzola, G., Cornillie, B., Rosemeyer, M. "Geographic and Stylistic variation of Spanish que-omission". Presented at the *Taaldag 2019 (Linguistic Society of Belgium)*, KU Leuven, Brussels.

-   Mazzola, G. (2019). "Acerca de la elisión de que en la historia del español". Presented at the *III Encuentro de Lingüística Hispánica en Bélgica*, KU Leuven, Leuven.
